theme = "identity"
disableKinds = ['taxonomy', 'term']
copyright = "2023 ProfileJP"

baseURL = "https://profile.jp.net/wis/"
title = "Wis - ProfileJP"

[params]
author = "Wis"
icon = "avatar/wis"
description = "Hello, World!"

[[params.social]]
name = "twitter"
icon = "brands fa-twitter"
url = "https://twitter.com/intent/user?user_id=2148889165"
