#hasCJKLanguage = true
languageCode = "en"
disableKinds = ['taxonomy', 'term']
theme = "identity"
copyright = "2023 ProfileJP"

baseURL = "https://profile.jp.net/wis/"
title = "Wis - ProfileJP"

[params]
author = "Wis"
icon = "avatar"
description = "Hello, World!"

[[params.social]]
name = "twitter"
icon = "brands fa-twitter"
url = "https://twitter.com/qn33"
